name: Release

on:
  release:
    types: [published]

jobs:
  build-full:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          ./build.sh

      - name: Deploy
        uses: WebFreak001/upload-asset@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ env.result_file_path }}
          mime: application/octet-stream
          name: ${{ env.result_file_name }}
